TARGET := DMALED
#C_SOURCES := $(wildcard ./User/*.c) 
#C_INCLUDES := -I"./User/" 
C_SOURCES += $(wildcard ./CharlieDriver/*.c) 
C_INCLUDES += -I"./CharlieDriver/" 


include ../../ch32v203.mk
